#!/bin/bash

# Bash script to join master node via kubeadm
# This script assumes you have already set up a Kubernetes master node
# Replace <MASTER_IP> with the IP address of your master node
# Replace <TOKEN> with the token generated by the master node
# Replace <DISCOVERY_HASH> with the discovery hash generated by the master node

sudo apt update
sudo apt-get install -y apt-transport-https ca-certificates curl gpg

curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

sudo apt update
sudo apt install -y kubectl kubelet kubeadm
sudo apt-mark hold kubectl kubelet kubeadm
sudo systemctl enable --now kubelet

cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF

sudo sysctl --system

#now setup containerd
wget https://github.com/containerd/containerd/releases/download/v2.1.4/containerd-2.1.4-linux-amd64.tar.gz
sudo tar Cxzvf /usr/local containerd-2.1.4-linux-amd64.tar.gz
sudo mkdir -p /etc/systemd/system
sudo wget -O /etc/systemd/system/containerd.service https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
sudo systemctl daemon-reload
sudo systemctl enable --now containerd

#now setup runc
sudo wget https://github.com/opencontainers/runc/releases/download/v1.3.1/runc.amd64
sudo install -m 755 runc.amd64 /usr/local/sbin/runc
sudo mkdir -p /etc/containerd

sudo sh -c "containerd config default > /etc/containerd/config.toml"
# sudo vim /etc/containerd/config.toml

# Set SystemdCgroup as true this is to enable systemd cgroup driver as it is default linux cgroup driver
sudo sed -i "/^\s*\[plugins\.'io.containerd.cri.v1.runtime'\.containerd\.runtimes\.runc\.options\]/a\            SystemdCgroup = true" /etc/containerd/config.toml

sudo systemctl restart containerd

#ip fowarder
sudo sysctl -w net.ipv4.ip_forward=1
sudo sysctl -p


if sudo systemctl status containerd | grep -q "running"; then
  echo "Containerd is running....."
else
  echo "Containerd failed to start....."
fi